### ISSUE TITLE
KubeSchedulerConfiguration v1beta2 is deprecated in v1.25 and will be removed in v1.26

### ISSUE THREAD

**Issue by criscola** [intel/platform-aware-scheduling#104]
According to [this](https://kubernetes.io/docs/reference/scheduling/config/) doc page, KubeSchedulerConfiguration v1beta2 is deprecated in v1.25 and will be removed in v1.26, therefore the `apiVersion` field of [this](https://github.com/intel/platform-aware-scheduling/tree/master/telemetry-aware-scheduling#extender-configuration) should be updated.

**Comment by madalazar** [comment]
Hi!

Thank you for reaching out! I will bring this to our next planning session and see when we can pick this up. I will come back with an update once this is set.
While here, we also need to understand what versions the PAS project will support moving forward.  The more versions we support the more complex our configuration script will become so we need to weigh the pros and cons.

Will try my best to keep you up-to-date!

**Comment by criscola** [comment]
Hi, the changes to the config are minimal so one should be able to update to v1 easily by changing the apiVersion field, of course this won't work for older versions (I believe v1 is from K8s v1.25 onwards). 

Unrelated to this, we are currently trying to create clusters with the TAS scheduler already installed through Cluster API; it's almost done so I will post my results soon if you want!

**Comment by togashidm** [comment]
Sure, it will be great to see how our project is helping out there!  Thank you!

**Comment by madalazar** [comment]
Hi,

Just wanted to let you know we updated TAS to be able to work with K8s 1.25 so the issues should be fixed https://github.com/intel/platform-aware-scheduling/commit/1e4739e87bc74a38c4cf2b4cd1743cd215167bd8 and https://github.com/intel/platform-aware-scheduling/commit/c0dc08728b01baf8cb8f9efdb78290052738c6c9.

For 1.26.0 I tested locally on my dev cluster and again, I was able to install TAS successfully with the fixes above.

I'm  going to close this issue, but feel free to reopen if you find other problems,
Thank you!
