### ISSUE TITLE
All pods in same node giving same power values.

### ISSUE THREAD

**Issue by adilGhaffarDev** [intel/platform-aware-scheduling#110]
In our cluster we have 2 worker nodes, the node_package_power_per_pod is giving same value for all pods that are in the same node. Below are the metrics output that we are getting:

- node_package_power_per_pod{created_by_kind="DaemonSet",created_by_name="calico-node",host_ip="192.168.111.101",host_network="true",instance="stable-kube-state-metrics.default.svc.cluster.local:8080",job="kube-state-metrics",namespace="kube-system",node="test1-775547f794-4sw9c",pod="calico-node-955qp",pod_ip="192.168.111.101",priority_class="system-node-critical"}	16.22732102030295

- node_package_power_per_pod{created_by_kind="DaemonSet",created_by_name="calico-node",host_ip="192.168.111.102",host_network="true",instance="stable-kube-state-metrics.default.svc.cluster.local:8080",job="kube-state-metrics",namespace="kube-system",node="test1-775547f794-744hm",pod="calico-node-q7gkd",pod_ip="192.168.111.102",priority_class="system-node-critical"}	11.588657717541842

- node_package_power_per_pod{created_by_kind="DaemonSet",created_by_name="collectd",host_ip="192.168.111.101",host_network="false",instance="stable-kube-state-metrics.default.svc.cluster.local:8080",job="kube-state-metrics",namespace="monitoring",node="test1-775547f794-4sw9c",pod="collectd-bzv9z",pod_ip="192.168.47.65",uid="f079c1d0-57c8-4d67-99d3-8333e7f43185"}	16.22732102030295
- node_package_power_per_pod{created_by_kind="DaemonSet",created_by_name="collectd",host_ip="192.168.111.102",host_network="false",instance="stable-kube-state-metrics.default.svc.cluster.local:8080",job="kube-state-metrics",namespace="monitoring",node="test1-775547f794-744hm",pod="collectd-bcsvl",pod_ip="192.168.50.3",uid="f2118a48-da62-4136-a83c-1c68239bd8d7"}	11.588657717541842
- node_package_power_per_pod{created_by_kind="DaemonSet",created_by_name="kube-proxy",host_ip="192.168.111.101",host_network="true",instance="stable-kube-state-metrics.default.svc.cluster.local:8080",job="kube-state-metrics",namespace="kube-system",node="test1-775547f794-4sw9c",pod="kube-proxy-l7qkl",pod_ip="192.168.111.101",priority_class="system-node-critical"}	16.22732102030295
- node_package_power_per_pod{created_by_kind="DaemonSet",created_by_name="kube-proxy",host_ip="192.168.111.102",host_network="true",instance="stable-kube-state-metrics.default.svc.cluster.local:8080",job="kube-state-metrics",namespace="kube-system",node="test1-775547f794-744hm",pod="kube-proxy-s7frc",pod_ip="192.168.111.102",priority_class="system-node-critical"}	11.588657717541842
- node_package_power_per_pod{created_by_kind="DaemonSet",created_by_name="node-exporter",host_ip="192.168.111.101",host_network="true",instance="stable-kube-state-metrics.default.svc.cluster.local:8080",job="kube-state-metrics",namespace="kube-system",node="test1-775547f794-4sw9c",pod="node-exporter-dbnmr",pod_ip="192.168.111.101",priority_class="system-node-critical"}	16.22732102030295
- node_package_power_per_pod{created_by_kind="DaemonSet",created_by_name="node-exporter",host_ip="192.168.111.102",host_network="true",instance="stable-kube-state-metrics.default.svc.cluster.local:8080",job="kube-state-metrics",namespace="kube-system",node="test1-775547f794-744hm",pod="node-exporter-mhdt2",pod_ip="192.168.111.102",priority_class="system-node-critical"}	11.588657717541842
- node_package_power_per_pod{created_by_kind="ReplicaSet",created_by_name="custom-metrics-apiserver-58dd7fb956",host_ip="192.168.111.101",host_network="false",instance="stable-kube-state-metrics.default.svc.cluster.local:8080",job="kube-state-metrics",namespace="custom-metrics",node="test1-775547f794-4sw9c",pod="custom-metrics-apiserver-58dd7fb956-db7tc",pod_ip="192.168.47.67"}	16.22732102030295
- node_package_power_per_pod{created_by_kind="ReplicaSet",created_by_name="descheduler-75c7857565",host_ip="192.168.111.102",host_network="false",instance="stable-kube-state-metrics.default.svc.cluster.local:8080",job="kube-state-metrics",namespace="kube-system",node="test1-775547f794-744hm",pod="descheduler-75c7857565-nbtst",pod_ip="192.168.50.9",priority_class="system-cluster-critical"}	11.588657717541842
- node_package_power_per_pod{created_by_kind="ReplicaSet",created_by_name="prometheus-deployment-bcddbd4cd",host_ip="192.168.111.101",host_network="false",instance="stable-kube-state-metrics.default.svc.cluster.local:8080",job="kube-state-metrics",namespace="monitoring",node="test1-775547f794-4sw9c",pod="prometheus-deployment-bcddbd4cd-q84nx",pod_ip="192.168.47.80"}	16.22732102030295
- node_package_power_per_pod{created_by_kind="ReplicaSet",created_by_name="stable-kube-state-metrics-77d8bd798",host_ip="192.168.111.102",host_network="false",instance="stable-kube-state-metrics.default.svc.cluster.local:8080",job="kube-state-metrics",namespace="default",node="test1-775547f794-744hm",pod="stable-kube-state-metrics-77d8bd798-n2n97",pod_ip="192.168.50.4"}	11.588657717541842

**Comment by killianmuldoon** [comment]
This is expected, but the metric is confusingly named or maybe just under-documented. The `node_package_power_per_pod` formula is in the [prometheus config](https://github.com/intel/platform-aware-scheduling/blob/master/telemetry-aware-scheduling/docs/power/prometheus/prometheus-config.yaml):
```bash
      rules:
      - record: node_package_power_avg
        expr: 100 * ((collectd_package_0_power_power/collectd_package_0_TDP_power_power) + (collectd_package_1_power_power/ collectd_package_1_TDP_power_power))/2 
      - record: node_package_power_per_pod
        expr:  kube_pod_info * on (node) group_left **node_package_power_avg**
```

It's not the power usage of a pod, it's the power usage of the node that the pod is on. In the power demo it's used to show how power metrics can be used to [drive workload autoscaling using the HPA](https://github.com/intel/platform-aware-scheduling/blob/master/telemetry-aware-scheduling/docs/power/power-autoscaler.yaml), but it's not actually tracking the power usage of the individual workloads.
