### ISSUE TITLE
Kube-scheduler is not choosing prioritized node by Telemetry Aware Scheduling

### ISSUE THREAD

**Issue by Sunnatillo** [intel/platform-aware-scheduling#111]
In the TAS logs we can see that it received  prioritize request

`1027 19:48:52.748142       1 telemetryscheduler.go:55] "Received prioritize request" component="extender"
I1027 19:48:52.754649       1 telemetryscheduler.go:190] "health_metric for nodes:  [ worker1 :0] [ worker2 :1]" component="extender"
I1027 19:48:52.756819       1 telemetryscheduler.go:131] "node priorities returned: [{worker1 10} {worker2 9}]" component="extender"
`

health_metric for worker1 is 0 and for worker2 is 1. TAS prioritizing  worker1 as given in the logs. 
But the pod is scheduled to worker2. 

`demo-app-55b7cffd5d-hn476                     0/1     Pending             0          0s     <none>          worker2   <none>           <none>
demo-app-55b7cffd5d-hn476                     0/1     ContainerCreating   0          0s     <none>          worker2   <none>           <none>
demo-app-55b7cffd5d-hn476                     0/1     ContainerCreating   0          1s     <none>          worker2   <none>           <none>
demo-app-55b7cffd5d-hn476                     1/1     Running             0          2s     10.10.189.96    worker2   <none>           <none>
`

here is the taspolicy

`apiVersion: telemetry.intel.com/v1alpha1
kind: TASPolicy
metadata:
  name: demo-policy
  namespace: default
spec:
  strategies:
    scheduleonmetric:
      rules:
      - metricname: health_metric
        operator: LessThan`
 
Why pod is scheduled to worker2? Is there some misconfiguration on my deployment?

**Comment by Sunnatillo** [comment]
kube-scheduler logs

`I1027 19:48:52.759571       1 trace.go:205] Trace[1755174988]: "Scheduling" namespace:default,name:demo-app-55b7cffd5d-hn476 (27-Oct-2022 19:48:52.597) (total time: 161ms):
Trace[1755174988]: ---"Computing predicates done" 91ms (19:48:52.689)
Trace[1755174988]: ---"Prioritizing done" 68ms (19:48:52.757)
Trace[1755174988]: [161.160364ms] [161.160364ms] END
`

**Comment by uniemimu** [comment]
The prioritization is not guaranteed to result in the Pod ending up scheduled into the node which TAS finds best suited.

The kubernetes scheduler takes into account many factors while considering the best suited node, and the priority score from TAS can be characterized as weak. One can fiddle with the `weight` in the scheduler configuration, to increase the impact of TAS.

You can trace the scoring decisions in the kube-scheduler by increasing the verbosity of kube-scheduler to at least 10 (-v=10 to the command line) . See: https://github.com/kubernetes/kubernetes/blob/5de293c425ec0cde9a2cf8917a69329bebcd0bbd/pkg/scheduler/schedule_one.go#L732

**Comment by Sunnatillo** [comment]
Thank you for your answer.
