### ISSUE TITLE
Warning about critical-pod non-functional

### ISSUE THREAD

**Issue by yengliong93** [intel/platform-aware-scheduling#114]
When running `helm install node-exporter telemetry-aware-scheduling/deploy/charts/prometheus_node_exporter_helm_chart`. a warning about critical pod popping out. 

> W1212 13:54:31.447663 280921 warnings.go:70] spec.template.metadata.annotations[scheduler.alpha.kubernetes.io/critical-pod]: non-functional in v1.16+; use the "priorityClassName" field instead

[This file makes use of the critical pod. ](https://github.com/intel/platform-aware-scheduling/blob/master/telemetry-aware-scheduling/deploy/charts/prometheus_node_exporter_helm_chart/templates/node-exporter-ds.yaml#L24)

While this does not stop the helm chart from being deployed, uncertain of the behavior that will result from the use of the non-functional property.

**Comment by madalazar** [comment]
Hi!
As far as I could tell there should be no issues with the chart up until K8s v1.26 as that is the most recent I have tested TAS with.
I will add an item into our backlog to address this and will come back with an estimation to when this will be picked up.

**Comment by madalazar** [comment]
Hi,
this problem has been fixed in https://github.com/intel/platform-aware-scheduling/pull/137 and PR is already merged in the master branch
