### ISSUE TITLE
Intermittent issue in TAS adding and deleting strategy

### ISSUE THREAD

**Issue by killianmuldoon** [intel/platform-aware-scheduling#56]
TAS seems to have intermittent issues when adding and deleting strategies. These issues are not clear in the logs created by TAS, and I haven't found away to repeat them deterministically. This issue possibly stems from the way TAS is adding and deleting policies from the cache. This issue will be used to track investigation and resolution for this issue. 

#55 Has a test which shows this issue by repeating the TASFilter end to end test.
Test run https://github.com/intel/platform-aware-scheduling/actions/runs/913029293 shows the issue at work.

**Comment by killianmuldoon** [comment]
#55 adds a change to the controller which appears to reliably fix the issue with the adding and deleting of strategies. This should not be merged until the actual source and flow of the diagnosed issue in the adding and deleting of policies is clearly identified.

**Comment by togashidm** [comment]
@killianmuldoon #55 is merged after our review.  Can we close this issue?

**Comment by killianmuldoon** [comment]
Thanks - looks like it's working!
