### ISSUE TITLE
Irrelevant TAS topic

### ISSUE THREAD

**Issue by Makonede** [intel/platform-aware-scheduling#97]
This repository has the TAS topic, which links to the topic page for tool-assisted speedrunning, not Telemetry Aware Scheduling. A more accurate topic to use would be `telemetry-aware-scheduling`, or simply removing the topic from the repository entirely.

**Comment by madalazar** [comment]
Hi!
Thank you for bringing this to our attention. It does seem indeed that the TAS topic doesn't fit.
Let me check to see if there are any approval processes required to make this change an will get back.

**Comment by madalazar** [comment]
Hi!
Made the changes seconds ago. Thank you for reaching out to us.
